services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181

  kafka:
    restart: always
    image: ches/kafka
    hostname: localhost
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <KAFKA_CONTAINER_IP_ADDRESS>
      ZOOKEEPER_IP: <ZOOKEEPER_CONTAINER_IP_ADDRESS>
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: 1
    
    depends_on:
      - zookeeper
