http:
    routers:
        allbackendrouter:
            rule: "Host(`husseinmac`)"
            service: allbackend
        adminblocker:
            rule: "Host(`husseinmac`) && Path(`/admin`)"
            service: blackhole
    services:
        blackhole:
            loadBalancer:
                servers:
        allbackend:
            loadBalancer:
                servers:
                    - url: "http://husseinmac:1111/"
                    - url: "http://husseinmac:2222/"
                    - url: "http://husseinmac:3333/"
                    - url: "http://husseinmac:4444/"