http:
    routers:
        unsecurerouter:
            rule: "Host(`traefikdemo2.ddns.net`)"
            service: allbackend
        allbackendrouter:
            rule: "Host(`traefikdemo2.ddns.net`)"
            service: allbackend
            tls:
                certResolver: myresolver
                options: tlsoptions
    services:
        allbackend:
            loadBalancer:
                servers:
                    - url: "http://husseinmac:1111/"
                    - url: "http://husseinmac:2222/"
                    - url: "http://husseinmac:3333/"
                    - url: "http://husseinmac:4444/"

tls:
    options:
        tlsoptions:
            minVersion: VersionTLS12