d=[
"Algeria,Algiers",
"Argentina,Buenos Aires",
"Australia,Canberra",
"Austria,Vienna",
"Belgium,Brussels",
"Brazil,Brasilia",
"Bulgaria,Sofia",
"Canada,Ottawa",
"Chile,Santiago",
"China,Beijing",
"Croatia,Zagreb",
"Cuba,Havana",
"Czech Republic,Prague",
"Denmark,Copenhagen",
"Ecuador,Quito",
"Egypt,Cairo",
"Estonia,Tallinn",
"Finland,Helsinki",
"France,Paris",
"Germany,Berlin",
"Greece,Athens",
"Hungary,Budapest",
"Iceland,Reykjavik",
"India,New Delhi",
"Indonesia,Jakarta",
"Iran,Tehran",
"Iraq,Baghdad",
"Ireland,Dublin",
"Israel,Jerusalem",
"Italy,Rome",
"Jamaica,Kingston",
"Japan,Tokyo",
"Lebanon,Beirut",
"Lithuania,Vilnius",
"Luxembourg,Luxembourg",
"Macedonia,Skopje",
"Madagascar,Antananarivo",
"Mexico,Mexico City",
"Monaco,Monaco",
"Morocco,Rabat",
"Nepal,Kathmandu",
"Netherlands,Amsterdam",
"New Zealand,Wellington",
"North Korea,Pyongyang",
"Norway,Oslo",
"Palestine,Ramallah",
"Paraguay,Asunción",
"Peru,Lima",
"Philippines,Manila",
"Poland,Warsaw",
"Portugal,Lisbon",
"Romania,Bucharest",
"Qatar,Doha",
"Russia,Moscow",
"Saudi Arabia,Riyadh",
"Singapore,Singapore",
"Slovakia,Bratislava",
"Slovenia,Ljubljana",
"South Africa,Pretoria",
"South Korea,Seoul",
"Spain,Madrid",
"Sweden,Stockholm",
"Switzerland,Bern",
"Taiwan,Taipei",
"Tunisia,Tunis",
"Turkey,Ankara",
"Ukraine,Kyiv",
"Uruguay,Montevideo",
"United Arab Emirates,Abu Dhabi",
"United Kingdom,London",
"United States of America,Washington D.C.",
"Venezuela,Caracas",
"Vatican City,Vatican City",
"Vietnam,Hanoi",
"Guyana,Georgetown",
"Libya,Tripoli",

"Afghanistan,Kabul",
"Andorra,Andorra la Vella",
"Albania,Tirana",
"Belarus,Minsk",
"Bosnia and Herzegovina ,Sarajevo",
"Burkina Faso,Ouagadougou",
"Cameroon,Yaoundé",
"Central African Republic,Bangui",
"Republic of the Congo,Brazzaville",
"Democratic Republic of the Congo,Kinshasa",
"Cote d'Ivoire,Yamoussoukro",
"Costa Rica,San Jose",
"Colombia,Bogotá",
"Bolivia,La Paz",
"Cabo Verde,Praia",
"Cyprus,Nicosia",
"Benin,Porto-Novo",
"Cambodia,Phnom Penh",
"Dominica,Roseau",
"Dominican Republic,Santo Domingo",
"Equatorial Guinea,Malabo",
"Guatemala,Guatemala City",
"Haiti,Port-au-Prince",
"Honduras,Tegucigalpa",
"Jordan,Amman",
"Kazakhstan,Astana",
"Kosovo,Pristina",
"Kuwait,Kuwait City",
"Laos,Vientiane",
"Kenya,Nairobi",
"Malaysia,Kuala Lumpur",
"Mali,Bamako",
"Malta,Valletta",
"Moldova,Chisinau",
"Pakistan,Islamabad",
"Panama,Panama City",
"San Marino,San Marino",
"Senegal,Dakar",
"Serbia,Belgrade",
"Seychelles,Victoria",
"Somalia,Mogadishu",
"Sri Lanka,Sri Jayawardenepura Kotte",
"Sudan,Khartoum",
"Tanzania,Dodoma",
"Thailand,Bangkok",
"Yemen,Sana'a",
"Zimbabwe,Harare",

"Antigua and Barbuda,Saint John's",
"Armenia,Yerevan",
"Azerbaijan,Baku",
"Angola,Luanda",
"Bahamas,Nassau",
"Bahrain,Manama",
"Bangladesh,Dhaka",
"Barbados,Bridgetown",
"Belize,Belmopan",
"Bhutan,Thimphu",
"Botswana,Gaborone",
"Brunei,Bandar Seri Begawan",
"Burundi,Bujumbura",
"Chad,N'Djamena",
"Comoros,Moroni",
"Djibouti,Djibouti",
"El Salvador,San Salvador",
"Eritrea,Asmara",
"Ethiopia,Addis Ababa",
"Fiji,Suva",
"Gabon,Libreville",
"Gambia,Banjul",
"Georgia,Tbilisi",
"Ghana,Accra",
"Grenada,St. George's",
"Guinea,Conakry",
"Guinea-Bissau,Bissau",
"Kiribati,South Tarawa",
"Kyrgyzstan,Bishkek",
"Latvia,Riga",
"Lesotho,Maseru",
"Liberia,Monrovia",
"Liechtenstein,Vaduz",
"Malawi,Lilongwe",
"Maldives,Male",
"Marshall Islands,Majuro",
"Mauritania,Nouakchott",
"Mauritius,Port Louis",
"Micronesia,Palikir",
"Mongolia,Ulaanbaatar",
"Montenegro,Podgorica",
"Mozambique,Maputo",
"Myanmar,Naypyidaw",
"Namibia,Windhoek",
"Nauru,Yaren District",
"Nicaragua,Managua",
"Niger,Niamey",
"Nigeria,Abuja",
"Oman,Muscat",
"Palau,Ngerulmud",
"Papua New Guinea,Port Moresby",
"Rwanda,Kigali",
"Saint Kitts and Nevis,Basseterre",
"Saint Lucia,Castries",
"Saint Vincent and the Grenadines,Kingstown",
"Samoa,Apia",
"Sao Tome and Principe,São Tomé",
"Sierra Leone,Freetown",
"Solomon Islands,Honiara",
"South Sudan,Juba",
"Suriname,Paramaribo",
"Swaziland,Mbabane",
"Syria,Damascus",
"Tajikistan,Dushanbe",
"Timor-Leste,Dili",
"Togo,Lomé",
"Tonga,Nuku'alofa",
"Trinidad and Tobago,Port of Spain",
"Turkmenistan,Ashgabat",
"Tuvalu,Funafuti",
"Uganda,Kampala",
"Uzbekistan,Tashkent",
"Vanuatu,Port Vila",
"Zambia,Lusaka",

/*"Cape Canaveral",
"Christ the Redeemer",
"The Great Chinese Wall",
"The Great Sphinx",
"The Eiffel Tower",
"Tower of Pisa",
"Mount Everest",
"Sagrada Familia",
"Big Ben",
"The Statue of Liberty",
"Forbidden City",
"The Pyramids of Giza",
"The Palace of Versailles",
"Acropolis",
"Trevi Fountain",
"Kremlin",
"Loch Ness",
"Atomium",
"Lascaux caves",
"Mont St. Michel",
"Piazza San Marco",
"The Grand Canyon",
"Millau Bridge",
"Rock of Gibraltar",
"The Empire State Building",
"Hollywood Sign",
"Times square",
"Louvre Museum",
"White House",
"Florence Cathedral",
"Las Vegas",
"Madrid Palace",
"Central Park",
"Sistine Chapel",
"Piazza del Campo",


"Machu Picchu",
"The Burj al Arab Hotel",
"St. Peter’s Cathedral",
"Kilimanjaro",
"Capitol Hill",
"Luxor Temple",
"Golden Gate Bridge",
"Burj Khalifa",
"Alcatraz",
"Ephesus",
"Manneken Pis",
"Mount Eden crater",
"North Cape",
"St. Basil’s Cathedral",
"Victoria Falls",
"The Great Buddha",
"Lotus Temple",
"The Colosseum",
"Abu Simbel",
"Petronas Twin Towers",
"Yellowstone",
"Niagara Falls",
"The Taj Mahal",
"Mount Fuji",
"Mecca",
"Auschwitz",
"Stonehenge",
"Mount Rushmore",
"Pentagon",
"Cape of Good Hope",
"Opera House",
"Parc Guell",
"Pompeii",
"Dead sea",

"Waterloo",
"Easter Island",
"Everglades",
"Cloud gate",
"Rialto Bridge",
"Willis Tower",
"Little mermaid statue",
"Tower Bridge",
"The Blue Mosque",
"Nevado Mismi",
"Table Mountain",
"Minaret of Jam",
"Angkor Wat",
"Faisal Mosque",
"Neuschwanstein castle",
"Golden Temple of Amritsar",
"Al Aqsa Mosque",
"Temple of Besakih",
"Chichen Itza",
"Bran Castle",
"Hagia Sophia",
"Uluru",
"Brandenburg Gate",
"Blue Domed Church",
"Taal lake",
"Alhambra",
"Kiyomizu-dera",
"Petra",
"Tombouctou",
"Kultury i Nauki Palace",
*/


/*"Hawaii,Honolulu",
"Alaska,Juneau",
"Washington,Olympia",
"Nevada,Carson City",
"New Mexico,Santa Fe",
"New York,Albany",
"Florida,Tallahassee",
"Illinois,Springfield",
"Ohio,Columbus",
"Rhode Island,Providence",
"South Carolina,Columbia",
"Texas,Austin",
"Utah,Salt Lake City",
"Virginia,Richmond",
"West Virginia,Charleston",
"Pennsylvania,Harrisburg",
"Massachusetts,Boston",
"North Carolina,Raleigh",
"Alabama,Montgomery",
"California,Sacramento",
"Colorado,Denver",
"Georgia,Atlanta",
"Michigan,Lansing",

"North Dakota,Bismarck",
"Montana,Helena",
"Nebraska,Lincoln",
"Arizona,Phoenix",
"Arkansas,Little Rock",
"New Hampshire,Concord",
"New Jersey,Trenton",
"Connecticut,Hartford",
"Delaware,Dover",
"Oklahoma,Oklahoma City",
"Idaho,Boise",
"Oregon,Salem",
"Indiana,Indianapolis",
"Iowa,Des Moines",
"Kansas,Topeka",
"South Dakota,Pierre",
"Kentucky,Frankfort",
"Tennessee,Nashville",
"Louisiana,Baton Rouge",
"Maine,Augusta",
"Maryland,Annapolis",
"Vermont,Montpelier",
"Minnesota,St. Paul",
"Mississippi,Jackson",
"Wisconsin,Madison",
"Missouri,Jefferson City",
"Wyoming,Cheyenne"*/



]